# Generated by Django 3.2 on 2021-05-02 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('regular', 'Regular'), ('square', 'Square')], default='Regular', max_length=50, verbose_name='type')),
                ('size', models.ForeignKey(default='medium', on_delete=django.db.models.deletion.CASCADE, to='home.pizzasize', verbose_name='size')),
                ('toppings', models.ManyToManyField(related_name='pizza', to='home.Topping', verbose_name='toppings')),
            ],
        ),
    ]
